repos:
  # to format code
  - repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest stable version
    hooks:
      - id: black
        args: [--line-length=110]
        files: ^src/shop/.*\.py$

  # to lint code
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=110]
        files: ^src/shop/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^src/shop/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^src/shop/.*\.py$
      - id: end-of-file-fixer
